INSERT INTO STATUSPEDIDO (STPDESCRICAO) VALUES ('À postar');
INSERT INTO STATUSPEDIDO (STPDESCRICAO) VALUES ('Em trânsito');
INSERT INTO STATUSPEDIDO (STPDESCRICAO) VALUES ('Entregue');
INSERT INTO STATUSPEDIDO (STPDESCRICAO) VALUES ('Concretizada');
INSERT INTO STATUSPEDIDO (STPDESCRICAO) VALUES ('Qualificada');
INSERT INTO STATUSPEDIDO (STPDESCRICAO) VALUES ('Reclamação');
INSERT INTO STATUSPEDIDO (STPDESCRICAO) VALUES ('Devolução');
INSERT INTO STATUSPEDIDO (STPDESCRICAO) VALUES ('Defeito');
INSERT INTO STATUSPEDIDO (STPDESCRICAO) VALUES ('Cancelada');
INSERT INTO STATUSPEDIDO (STPDESCRICAO) VALUES ('Extravio');

INSERT INTO TIPOAVALIACOES (TIVDESCRICAO) VALUES ('POSITIVA');
INSERT INTO TIPOAVALIACOES (TIVDESCRICAO) VALUES ('NEGATIVA');
INSERT INTO TIPOAVALIACOES (TIVDESCRICAO) VALUES ('NEUTRA');

INSERT INTO STATUSANUNCIO (STADESCRICAO) VALUES ('Ativo');
INSERT INTO STATUSANUNCIO (STADESCRICAO) VALUES ('Pausado');
INSERT INTO STATUSANUNCIO (STADESCRICAO) VALUES ('Finalizado');

INSERT INTO TIPOANUNCIO (TIADESCRICAO) VALUES ('PREMIUM');
INSERT INTO TIPOANUNCIO (TIADESCRICAO) VALUES ('CLÁSSICO');
INSERT INTO TIPOANUNCIO (TIADESCRICAO) VALUES ('GRÁTIS');

INSERT INTO ANUNCIO VALUES (0, 25, 8, 'Mochila Feminina', 72.90, '2016-05-19', true);
INSERT INTO ANUNCIO VALUES (0, 25, 8, 'Bolsa de Couro', 89.90, '2016-05-19', true);
INSERT INTO ANUNCIO VALUES (0, 25, 8, 'Cinto Calvin Klein', 64.90, '2016-05-19', true);