--STATUS DE PEDIDO
INSERT INTO STATUSPEDIDO (STPDESCRICAO) VALUES ('À postar');
INSERT INTO STATUSPEDIDO (STPDESCRICAO) VALUES ('Em trânsito');
INSERT INTO STATUSPEDIDO (STPDESCRICAO) VALUES ('Entregue');
INSERT INTO STATUSPEDIDO (STPDESCRICAO) VALUES ('Concretizada');
INSERT INTO STATUSPEDIDO (STPDESCRICAO) VALUES ('Qualificada');
INSERT INTO STATUSPEDIDO (STPDESCRICAO) VALUES ('Reclamação');
INSERT INTO STATUSPEDIDO (STPDESCRICAO) VALUES ('Devolução');
INSERT INTO STATUSPEDIDO (STPDESCRICAO) VALUES ('Defeito');
INSERT INTO STATUSPEDIDO (STPDESCRICAO) VALUES ('Cancelada');
INSERT INTO STATUSPEDIDO (STPDESCRICAO) VALUES ('Extravio');

--STATUS DE ANÚNCIOS
INSERT INTO STATUSANUNCIO (STADESCRICAO) VALUES ('Ativo');
INSERT INTO STATUSANUNCIO (STADESCRICAO) VALUES ('Pausado');
INSERT INTO STATUSANUNCIO (STADESCRICAO) VALUES ('Finalizado');

-- TIPOS DE ANÚNCIO
INSERT INTO TIPOANUNCIO VALUES (0,'PREMIUM',0.16);
INSERT INTO TIPOANUNCIO VALUES (0,'CLÁSSICO',0.10);
INSERT INTO TIPOANUNCIO VALUES (0,'GRÁTIS',0);

--TIPOS DE AVALIAÇÕES
INSERT INTO TIPOAVALIACOES VALUES (0, 'Positiva');
INSERT INTO TIPOAVALIACOES VALUES (0, 'Negativa');
INSERT INTO TIPOAVALIACOES VALUES (0, 'Neutra');
INSERT INTO TIPOAVALIACOES VALUES (0, 'Sem avaliação');

--MOVIMENTAÇÕES
INSERT INTO TIPOMOVIMENTACAO VALUES (0,'ACERTO', TRUE);
INSERT INTO TIPOMOVIMENTACAO VALUES (0,'INVESTIMENTO', TRUE);
INSERT INTO TIPOMOVIMENTACAO VALUES (0,'OUTROS GASTOS', FALSE);
INSERT INTO TIPOMOVIMENTACAO VALUES (0,'COMPRA MERC.', TRUE);
INSERT INTO TIPOMOVIMENTACAO VALUES (0,'RETIRADA', FALSE);
INSERT INTO TIPOMOVIMENTACAO VALUES (0,'TAXA', FALSE);
INSERT INTO TIPOMOVIMENTACAO VALUES (0,'REEMBOLSO', FALSE);
INSERT INTO TIPOMOVIMENTACAO VALUES (0,'ENT. SALDO ML', TRUE);
INSERT INTO TIPOMOVIMENTACAO VALUES (0,'SAI. CAIXA', FALSE);
INSERT INTO TIPOMOVIMENTACAO VALUES (0,'ENT. CAIXA', TRUE);
INSERT INTO TIPOMOVIMENTACAO VALUES (0,'VENDA', TRUE);

--CLIENTES
INSERT INTO CLIENTE VALUES (0,'Rosimeire Fabricio De Oliveira','rosimeireoliveira78@outlook.com');
INSERT INTO CLIENTE VALUES (0,'Helio Da Silva Macedo','kelezaopita@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Edinice Simonetti','edinicesimon@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Leonice Teixeira','leonicebeatriz@ig.com.br');
INSERT INTO CLIENTE VALUES (0,'Jeane Sawano De Siqueira','sawanokaras@outlook.com');
INSERT INTO CLIENTE VALUES (0,'Katia Conceição De Jesus','katiacj@yahoo.com.br');
INSERT INTO CLIENTE VALUES (0,'Evelyn Drager','eve.fd2000@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Lorena De Sousa Teixeira','lorena.s.teixeira@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Caroline Borba De Souza','carol.bds@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Layde Ramos','layders88@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Gabriela Lauer','gabriela_lauer@yahoo.com');
INSERT INTO CLIENTE VALUES (0,'Maria De Lourdes Ferreira','ferreiramaria982@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Ana Claudia Vieira','anacclaudia.acv@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Rosimeire Fabricio De Oliveira','rosimeireoliveira78@outlook.com');
INSERT INTO CLIENTE VALUES (0,'Paola Assumpção','pah.assumpcao@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Bruna Lemos','brunal-s@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Rosa Maria Pinheiro Batista','rosapbatista@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Loughas Souza','loughas@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Alessandra Ramos Costa','alessandra.rcosta@yahoo.com.br');
INSERT INTO CLIENTE VALUES (0,'Naiara Battagy Damim','naiaradamim@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Andréa Cotta Lamas Cotta','andrea-cotta@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Adrieli Rovea','Adrieli.rovea@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Adriana Luz Fernandes','luz.adrian@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Helaine Baldrigues','helainebaldrigues@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Helen Pinheiro','helenpsv@outlook.com');
INSERT INTO CLIENTE VALUES (0,'Elisangela Aparecida','elisangelapoppet@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Denise Crespo De Oliveira','carlaoliveira2789@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Elizabete Machado','elizabetemachado@yahoo.com');
INSERT INTO CLIENTE VALUES (0,'Marcia Miranda Ferreira','marciamiranda560@yahoo.com.br');
INSERT INTO CLIENTE VALUES (0,'Rodrigo Alves','rpa_bituruna93@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Gabrielle De Almeida','martahabastos@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Bruna Borges','bruna_b_dasilva@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Leonardo Marques Verona','leomarques20@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Josue Santos Almeida','josuesantos@metrosp.com.br');
INSERT INTO CLIENTE VALUES (0,'Ricardo Pereira Alves','ricardopereira_77@yahoo.com.br');
INSERT INTO CLIENTE VALUES (0,'Lucélia Antunes S. Fraga','lucelia.s.fraga@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Raphael Agostini Marques','raphael_a.m@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Diana Dos Santos','dianadossantos2008@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Eduardo Tomaz','edduh2012@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Vera Lúcia Aparício','veraingleses@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Wallace De Andrade Souza','baiaodevaneio@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Tatiane Hoffmann','tati_hof@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Renata Silva','enata_shilva100@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Flavia Sonego','flavia.1611@hotmail.com ');
INSERT INTO CLIENTE VALUES (0,'Bianca Mayra','lisbibi@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Vaneide Silva','vaneidesilva2010@yahoo.com.br');
INSERT INTO CLIENTE VALUES (0,'Djenany Pommerening','djenany_dije@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Robson Sanches','rob-sanches@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Paola Bandera','paolabandera@outlook.com');
INSERT INTO CLIENTE VALUES (0,'Isa Shideko','contatonosite@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Carla Beatriz','c.bmartins27@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Waldemilson Reis Da Silva','silvawaldemilson@yahoo.com.br');
INSERT INTO CLIENTE VALUES (0,'Mari Vieira','maricontrafogo@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Lilian Paula Dos Reis','lilianreis.ge@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Nilsa Santos','snilza85@yahoo.com.br');
INSERT INTO CLIENTE VALUES (0,'Ana Sousa','sousa.anapc@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Emmanuelle Louise Nogueira','louisanouqueira@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Fernanda Graziele Santana','fgsmotta2011@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Gilmara Tavares Nascimento','maracardosomara@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Wellida Fabiana Souza','wellfab@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Hannelise Riemer','hanneri@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Gilziane Maria Teixeira','gilzianeteixeira@bol.com.br');
INSERT INTO CLIENTE VALUES (0,'Virginia Lima','vivi-lima01@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Marly Heloisa Heloisa','marly.helo@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Keli Peçanha','keli_pecanha@yahoo.com.br');
INSERT INTO CLIENTE VALUES (0,'Leonardo Dlugosz','leonardohelp@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Pablinny Galdino','pablinnyg@yahoo.com.br');
INSERT INTO CLIENTE VALUES (0,'Jaqueline Azevedo','jaque.c.azevedo@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Hayla Cristian Dourado Santos','hayla-cristian@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Jahmmeson Borges Da Silva','jborgescv@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Flavio Lucio De Moraes Lucio','flavioluciodemoraes@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Wanessa Gonçalves','waanessag@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Gabriela Souza','gabrielaalves44@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Andreia Abdelhay','andreia.bruce.abdelhay@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Larissa Holanda Rangel','larissaholandarangel@outlook.com');
INSERT INTO CLIENTE VALUES (0,'Carla Fernanda Silva Melocro','fernandamelocro@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Jéssica Araújo','jessycagm@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Gleicy Palmeira','gleicypalmeira19@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Maria Da Conceição Amorim Melo','maria.melo@logoplaste.com');
INSERT INTO CLIENTE VALUES (0,'Sonia Maria De Oliveira','sooliveira31@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Marcos Andrade','marcosandrade80@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Lais Pereira','laisfspereira@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Anne Caroline Menezes Santos','ac.santos@rocketmail.com');
INSERT INTO CLIENTE VALUES (0,'Joana Hughes','joana.hughes@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Ana Paula Alves De Melo','anaamelo@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Carlos Altino Machado Mattoso','altinomattoso@uol.com.br');
INSERT INTO CLIENTE VALUES (0,'Vanessa Vanzella','vanessavanzella@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Simone Lourenço','simonicas@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Samara Costa','samara.ng6@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Lorrayne Joana','lorraynne018@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Beatriz Da Silva Melo','bhiamello@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Leticia Cosmo','leticiacosmocarvalho@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Matheus Romano','matheuscontag@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Mateus Matos Ferreira','mateus.biologiaufs@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Elisangela Ferreira','elislferreira@yahoo.com.br');
INSERT INTO CLIENTE VALUES (0,'Thaysa Calandino','thaysa_calandino@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Meyriane Da Silva','mdasilvaassis@yahoo.com.br');
INSERT INTO CLIENTE VALUES (0,'José Santos','jose1975antoniosantos@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Amanda Beatriz','amandabeatrizsilva@outlook.com');
INSERT INTO CLIENTE VALUES (0,'Ludiceia Moreira','lmanjos@ig.com.br');
INSERT INTO CLIENTE VALUES (0,'Paloma Ferreira','ferreira-paloma@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Karina Silva Rodrigues','ka.20srodrigues@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Janaina Brito Vieira','janaina.vieirabrito@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Naiara Moreira','naiara.estrela@live.com');
INSERT INTO CLIENTE VALUES (0,'Elaine Maria Santos Souto','emss.1@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Fabio Sales','fabiocristo2009@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Adriana Pinto','adr.araujop@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Suelem Barbosa','singsuelem6@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Sabrina Simas','sasasimass@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Natalia Ferreira','natalinha_leaozinha@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Felipe Gabler','felipegabler@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Vanessa Freire','tiumpurawn@yahoo.com.br');
INSERT INTO CLIENTE VALUES (0,'Rosana Rodrigues Santiago','rosanasantiago2@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Rosana Oliveira','ro3570515@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Tiago De Miranda Carvalho','tiagocarvalho9979@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Márcia Teixeira','marciatxr.mt@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Bianca Zanon','bianca.zanon@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Marcia Costa','marciacqv@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Andrea Firmino Scarparo','a_scarparo@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Luane Nathalyne','luane2125@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Heliaquine Andrade Andrade','heliaquine@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Monique Guimarães','moniquesilvaguimaraes15@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Rosangela Manfredi','rosa.mar.sol@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Denise G D G Abrão','denisedelfino@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Enaldo Alcantara Reis Enaldo','yendion@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Edilene Aparecida De Carvalho Carvalho','dany-talitha@outlook.com');
INSERT INTO CLIENTE VALUES (0,'Verônica Ferreira','veronicaferreira95@yahoo.com.br');
INSERT INTO CLIENTE VALUES (0,'Webert Vimiciuz','webertvinicius2@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Carlos Claiton Coimbra','carlosclaitoncoimbra@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Roberto Da Conceição Silva','robertoc26silva@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Magdos Xavier Monteiro Xavier','magdos.xm@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Pryscila Camilo','pry_camilo@yahoo.com.br');
INSERT INTO CLIENTE VALUES (0,'Jéssica Dorneles Da Silva','jessica_dorneles@live.com');
INSERT INTO CLIENTE VALUES (0,'Kelycristina De Souza Souza','kelycristina.souza@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Matheus Lameu','matheus.lameu@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Valmir Andrade','valmirandrade159@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Laisa Cristina Duarte Silva','laisaduarte96@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Angélica Paula Moretto','angelica@aguiaseguros.com.br');
INSERT INTO CLIENTE VALUES (0,'Flavia Passos','flaviapassos14@live.com');
INSERT INTO CLIENTE VALUES (0,'Thiago Calheiros','tgc.calheiros@ig.com.br');
INSERT INTO CLIENTE VALUES (0,'Ana Oliveira','ana_lynda13@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Edilson Jose','asthorjean@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Eliza Mara Batista','eliza_mbatista@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Jerônimo Souza De Oliveira','oliveirajeronimo@yahoo.com.br');
INSERT INTO CLIENTE VALUES (0,'Cicero Castelo Branco','symbolcomunicacao@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Niedja Ossola','niedjasc@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Vera Lucia Pinheiro Da Platina','vera.platina@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Eni Nascimento','enitamv@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Lais Mota','laismotadorosario_@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Jhennifer Nunes','jhennifermonise85@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Auane Samira Barbosa','auane.samira@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Jaime Silva','guidyribeiro@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Karla Paulina Botelho','karla-botello-32@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Anderson Lima','contatoup@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Kadson Teixeira De Sousa','kknabalada14@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Thamires Francieli Da Silva','thamiresfranciele2@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Ítla Santos','itla_santos@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Vera Cavaliere','verabellei@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Claudirene Eduardo Sabino','bellyceci_2010@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Isabela Coelho','isabelacoelhomoreira@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Ianca Pereira','ianca.pereira6@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Wagner Dias','eng.dias17@outlook.com');
INSERT INTO CLIENTE VALUES (0,'Sandra Alves De Souza','ssouza@colmagno.com.br');
INSERT INTO CLIENTE VALUES (0,'Rosane Cristina','ro.cristina_@outlook.com');
INSERT INTO CLIENTE VALUES (0,'Wilma De Souza','miminha.souza@yahoo.com.br');
INSERT INTO CLIENTE VALUES (0,'Marisa Seabra','marisaseabra@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Jamile Carvalho Da Silva Sousa','jamilecarvalhosousa@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Francisca Sampaio','fraan_samppayyo@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Laura Lazzarotto','laulazaroto@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Marinalva Martins','marinalvamartins235@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Joao Antonio Baloneck','joaobaloneck@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Evilaine Teixeira','evilainet@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Camila Cavalheiro','mylazinhaaa@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Adaiane Perboni Neto','adaianeperboni@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Paloma Oliveira','p.alice1@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Pamela Costa','pamelacosta.com@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Jaqueline Barbosa','jaquilegiao@bol.com.br');
INSERT INTO CLIENTE VALUES (0,'Irma Aparecida Mantovani','duirmabi@yahoo.com.br');
INSERT INTO CLIENTE VALUES (0,'Michael Augusto Da Rosa','spfc_michael@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Rafael Bueno','rafaelbuenofh@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Viviane Souza',' vivianny_2013@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Antonio D Isaias','antonio.isaias@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Ângela Gabriela','gabriela.angela@outlook.com');
INSERT INTO CLIENTE VALUES (0,'Alfredo Francisco Berneira','aberneira13@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Jose Hilario Pereira Da Silva','jhipsi@terra.com.br');
INSERT INTO CLIENTE VALUES (0,'Luiz Gonçalves','lgluizgoncalves@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Patricia Cunha','patriciabujica@yahoo.com.br');
INSERT INTO CLIENTE VALUES (0,'Wanda Lucia Ferraço','wandaferraco@bol.com.br');
INSERT INTO CLIENTE VALUES (0,'Silvia Mota','silviaphl11@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Nayara Silva','nayara_silva.25@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Jarbas De Oliveira','jvesoliveira002@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Paola Vieira','paolavieira2207@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Ellen Moraes','lili_ellen@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Denise Carvalho','denny_dance@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Jose Roberto Arroyo','jamile_arroyo1@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Vinicius Andrade','viniciusseixas2009@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Wallace Santos','wallace.santos@apsis.com.br');
INSERT INTO CLIENTE VALUES (0,'Danielle Quiozini','dani_quiozini@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Kleiton Nascimento','magrokiller@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Ricardo Pereira Vieira','fenix22ll@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Ednaldo Renovato Renovato','anapaulamengao@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Monica Martins','monicamartins60315@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Paulo Araujo','pga900@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Mariane Chaves','marianesouza0045@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Luciano Elias Ferreira','lucianoelias16@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Deivid Renan Borges','deivid_renan@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Crecencio Carneiro','crecenciocarneiro@yahoo.com.br');
INSERT INTO CLIENTE VALUES (0,'Altair Narciso Narciso','casadacamiseta2016@gmail.com');
INSERT INTO CLIENTE VALUES (0,'João Paulo','paocomovo1@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Ellen Araujo','ellencrystie@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Rayane Nascimento','rayanny.pfuo@gmail.com');
INSERT INTO CLIENTE VALUES (0,'Elza Josefa Andrade','beteandilha@yahoo.com.br');
INSERT INTO CLIENTE VALUES (0,'Nilza Vargas','agdatean@yahoo.com.br');
INSERT INTO CLIENTE VALUES (0,'Juliana De Souza Mendonça','juliaejulianasouza@hotmail.com');
INSERT INTO CLIENTE VALUES (0,'Kleiton Luiz','kleitonluizgoncalves@live.com');

-- ANÚNCIOS
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'MOCHILA BOLSA FEMININA ESCOLAR UNIVERSITÁRIA IMPORTADA!!!' , 69.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'BOLSA MOCHILA ESCOLAR FEMININA COM ESTAMPA DE PÁSSAROS' , 49.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'MOCHILA LONA FEMININA BIGODE MUSTACHE FACUL ESCOL PROMOÇÃO' , 54.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'BOLSA MOCHILA ESCOLAR FEMININA COM ESTAMPA DE CORUJA' , 45.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'BOLSA MOCHILA ESCOLAR FEMININA COM ESTAMPA DE LETRAS' , 49.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'BOLSA MOCHILA ESCOLAR FEMININA ESTAMPA DE PÁSSAROS CORES !!' , 69.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'BOLSA SACO FEMININA COM FRANJA TRANVERSAL EM COURO / CAMURÇA' , 79.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'MOCHILA FEMININA BOLSA COURO SINTÉTICO PRODUTO IMPORTADO' , 69.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'MOCHILA LONA FEMININA BIGODE MUSTACHE FACUL ESCOL PROMOÇÃO' , 49.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'MOCHILA BOLSA FEMININA ESCOLAR UNIVERSITÁRIA IMPORTADA!!! (ESTAMPADAS)' , 79.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'MOCHILA BOLSA FEMININA ESCOLAR BIGODE IMPORTADA!!!' , 69.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'MOCHILA BOLSA FEMININA ESCOLAR UNIVERSITÁRIA IMPORTADA!!!' , 74.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'BOLSA MOCHILA ESCOLAR FEMININA ESTAMPA DE PÁSSAROS CORES !!' , 59.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'MOCHILA BOLSA FEMININA XADREZ UNIVERSITÁRIA VERMELHA E PRETA' , 54.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'PENDRIVE ROMERO BRITO 16GB' , 30 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'MOCHILA BOLSA FEMININA ESCOLAR UNIVERSITÁRIA IMPORTADA!!! (ANTIGO)' , 85.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'MOCHILA BOLSA FEMININA ESCOLAR UNIVERSITÁRIA IMPORTADA!!! (ANTIGO)' , 79.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'CAPA CELULAR TAMPA TRASEIRA MOTO G 1º E 2º GERAÇÃO MADEIRA' , 15.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'CAPA CELULAR TAMPA TRASEIRA MOTO G 1º E 2º GERAÇÃO MADEIRA' , 14.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'MOCHILA DE BIGODES (ANTIGO)' , 64.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'MOCHILA DE PASSAROS (ANTIGO)' , 51.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'MOCHILA DE PASSAROS (ANTIGO)' , 49.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'MOCHILA DE COURO (ANTIGO)' , 79.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 2 , 'CAPA CELULAR TAMPA TRASEIRA MOTO G 1º E 2º GERAÇÃO MADEIRA' , 10.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 2 , 'MOCHILA BOLSA FEMININA XADREZ UNIVERSITÁRIA VERMELHA E PRETA' , 54.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'MOCHILA BOLSA FEMININA ESCOLAR UNIVERSITÁRIA IMPORTADA!!!' , 59.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 2 , 'MOCHILA BOLSA FEMININA ESCOLAR UNIVERSITÁRIA IMPORTADA!!!' , 59.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 2 , 'BOLSA SACO FEMININA COM FRANJA TRANVERSAL EM COURO / CAMURÇA' , 69.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 2 , 'MOCHILA BOLSA FEMININA ESCOLAR UNIVERSITÁRIA IMPORTADA!!!' , 69.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 2 , 'BOLSA MOCHILA ESCOLAR FEMININA ESTAMPA DE PÁSSAROS CORES !!' , 69.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 2 , 'CAPA CELULAR TAMPA TRASEIRA MOTO G 3º GERAÇÃO MADEIRA' , 10.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'BOLSA FEMININA TOMMY HILFIGER SACOLA IMPORTADA PROMOÇÃO !' , 45 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 2 , 'MOCHILA FEMININA BOLSA COURO SINTÉTICO PRODUTO IMPORTADO' , 69.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 2 , 'BOLSA NIKE FEMININA HERITAGE LANÇAMENTO' , 64.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 2 , 'MOCHILA JEANS E CAMURÇA ARTESANAL FEMININA MASCULINO' , 99.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 2 , 'BOLSA MOCHILA ESCOLAR FEMININA ESTAMPA DE PÁSSAROS CORES !!' , 59.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 2 , 'BOLSA NIKE FEMININA HERITAGE LANÇAMENTO' , 79.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'BOLSA FEMININA CHANNEL LE BOY EM COURO IMPORTADA' , 89.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'MOCHILA BOLSA FEMININA LONA UNIVERSITÁRIA ESCOLAR' , 39.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'CINTO SOCIAL MASCULINO EM COURO LOUIS VITON' , 45 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'MOCHILA BOLSA FEMININA LONA UNIVERSITÁRIA ESCOLAR' , 44.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 2 , 'BOLSA FEMININA CHANNEL LE BOY EM COURO IMPORTADA' , 129.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 2 , 'BOLSA FEMININA IMPORTADA LE BOY INSPIRED PEQUENA' , 129.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'BOLSA FEMININA LE BOY INSPIRED MÉDIA CHANNEL FRETE GRÁTIS !' , 159.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'BOLSA FEMININA LE BOY INSPIRED MÉDIA CHANNEL FRETE GRÁTIS !' , 159.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 1 , 'BOLSA FEMININA COURO FRETE GRÁTIS ! (MÉDIA)' , 159.9 , '2016-05-21', true);
INSERT INTO ANUNCIO VALUES (0 ,1 , 2 , 'MOCHILA BOLSA FEMININA ESCOLAR UNIVERSITÁRIA IMPORTADA!!!' , 72.9 , '2016-05-21', true);

--PRODUTO
INSERT INTO PRODUTO VALUES (0,'MOCHILA BEGE DE PÁSSAROS', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA ROSA DE PÁSSAROS', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA AZUL DE PÁSSAROS', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA PRETA DE PÁSSAROS', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA VERMELHA DE LETRAS', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA BEGE DE CORUJA', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA CINZA DE CORUJA', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA PRETA DE CORUJA', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA AMARELA DE CORUJA', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA AZUL DE CORUJA', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA ROSA DE CORUJA', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA VERDE DE BIGODES', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA LISTRADA PRETA', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA LISTRADA AZUL', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA LISTRADA VERMELHA', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA LISTRADA ROSA', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA BEGE DE PÁSSAROS', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA ROSA DE PÁSSAROS', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA AZUL DE PÁSSAROS', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA PRETA DE PÁSSAROS', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA PRETA DE COURO', 1 ,25, 4, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA CARAMELO DE COURO', 1 ,40, 2, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA MARROM DE COURO', 1 ,40, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA VERMELHA DE COURO', 1 ,40, 1, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA BEGE CLARA DE COURO', 1 ,40, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA  AZUL DE BIGODES', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA BEGE DE BIGODES', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA XADREZ VERMELHA', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA XADREZ AZUL', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA CINZA DE ELEFANTES', 1 ,25, 1, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA PRETA DE ELEFANTES', 1 ,25, 1, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA PARA NOTEBOOK PRETA', 1 ,40, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'BOLSA COM FRANJAS MARROM AMARELADO', 1 ,33, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'BOLSA COM FRANJAS BEGE', 1 ,33, 1, TRUE);
INSERT INTO PRODUTO VALUES (0,'BOLSA COM FRANJAS MARROM', 1 ,33, 1, TRUE);
INSERT INTO PRODUTO VALUES (0,'PENDRIVE ROMERO BRITO', 1 ,30, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'CAPA DE MOTO G1', 1 ,5, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'CAPA DE MOTO G2', 1 ,5, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'CAPA DE MOTO G3', 1 ,5, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA AZUL DE COURO (ESCURO)', 1 ,40, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA PRETA PÁSSAROS (NOVO)', 1 ,40, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA AZUL PÁSSAROS (NOVO)', 1 ,40, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA AMARELA PÁSSAROS (NOVO)', 1 ,40, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'BOLSA NIKE PRETA', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'BOLSA NIKE BRANCA', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'BOLSA TOMMY AZUL', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'BOLSA TOMMY VERMELHA', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA ROSA  PÁSSAROS (NOVO)', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'BOLSA LOUIS VUITTON PRETA + BOLSINHA', 1 ,25, 2, TRUE);
INSERT INTO PRODUTO VALUES (0,'BOLSA LOUIS VUITTON BRANCA + BOLSINHA', 1 ,25, 2, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA JEANS AZUL', 1 ,50, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'BOLSA CHANNEL BORDEAUX (PEQUENA)', 1 ,40, 1, TRUE);
INSERT INTO PRODUTO VALUES (0,'BOLSA CHANNEL CARAMELO (PEQUENA)', 1 ,40, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'BOLSA CHANNEL PRETA (PEQUENA)', 1 ,40, 2, TRUE);
INSERT INTO PRODUTO VALUES (0,'BOLSA CHANNEL MARROM (PEQUENA)', 1 ,40, 2, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA ROSA DE COURO', 1 ,40, 2, TRUE);
INSERT INTO PRODUTO VALUES (0,'BOLSA CHANNEL PRETA (MÉDIA)', 1 ,50, 5, TRUE);
INSERT INTO PRODUTO VALUES (0,'BOLSA CHANNEL CARAMELO (MÉDIA)', 1 ,50, 3, TRUE);
INSERT INTO PRODUTO VALUES (0,'BOLSA NIKE COURO PRETA', 1 ,33, 2, TRUE);
INSERT INTO PRODUTO VALUES (0,'BOLSA NIKE COURO BRANCA', 1 ,33, 1, TRUE);
INSERT INTO PRODUTO VALUES (0,'CINTO CALVIN KLEIN', 1 ,25, 0, TRUE);
INSERT INTO PRODUTO VALUES (0,'MOCHILA AZUL DE COURO (CLARA)', 1 ,40, 0, TRUE);

INSERT INTO PRODUTOANUNCIO VALUES (1,21);
INSERT INTO PRODUTOANUNCIO VALUES (1,22);
INSERT INTO PRODUTOANUNCIO VALUES (1,23);
INSERT INTO PRODUTOANUNCIO VALUES (1,24);
INSERT INTO PRODUTOANUNCIO VALUES (1,25);
INSERT INTO PRODUTOANUNCIO VALUES (3,12);
INSERT INTO PRODUTOANUNCIO VALUES (3,26);
INSERT INTO PRODUTOANUNCIO VALUES (3,32);
INSERT INTO PRODUTOANUNCIO VALUES (8,34);
INSERT INTO PRODUTOANUNCIO VALUES (8,35);
INSERT INTO PRODUTOANUNCIO VALUES (9,12);
INSERT INTO PRODUTOANUNCIO VALUES (9,27);
INSERT INTO PRODUTOANUNCIO VALUES (12,21);
INSERT INTO PRODUTOANUNCIO VALUES (12,24);
INSERT INTO PRODUTOANUNCIO VALUES (13,1);
INSERT INTO PRODUTOANUNCIO VALUES (13,2);
INSERT INTO PRODUTOANUNCIO VALUES (13,3);
INSERT INTO PRODUTOANUNCIO VALUES (13,4);
INSERT INTO PRODUTOANUNCIO VALUES (24,38);
INSERT INTO PRODUTOANUNCIO VALUES (25,29);
INSERT INTO PRODUTOANUNCIO VALUES (26,28);
INSERT INTO PRODUTOANUNCIO VALUES (26,29);
INSERT INTO PRODUTOANUNCIO VALUES (27,29);
INSERT INTO PRODUTOANUNCIO VALUES (28,33);
INSERT INTO PRODUTOANUNCIO VALUES (28,34);
INSERT INTO PRODUTOANUNCIO VALUES (28,36);
INSERT INTO PRODUTOANUNCIO VALUES (29,21);
INSERT INTO PRODUTOANUNCIO VALUES (29,22);
INSERT INTO PRODUTOANUNCIO VALUES (29,23);
INSERT INTO PRODUTOANUNCIO VALUES (29,24);
INSERT INTO PRODUTOANUNCIO VALUES (29,25);
INSERT INTO PRODUTOANUNCIO VALUES (29,33);
INSERT INTO PRODUTOANUNCIO VALUES (29,40);
INSERT INTO PRODUTOANUNCIO VALUES (29,56);
INSERT INTO PRODUTOANUNCIO VALUES (31,39);
INSERT INTO PRODUTOANUNCIO VALUES (32,46);
INSERT INTO PRODUTOANUNCIO VALUES (32,47);
INSERT INTO PRODUTOANUNCIO VALUES (34,44);
INSERT INTO PRODUTOANUNCIO VALUES (34,45);
INSERT INTO PRODUTOANUNCIO VALUES (35,51);
INSERT INTO PRODUTOANUNCIO VALUES (36,41);
INSERT INTO PRODUTOANUNCIO VALUES (36,42);
INSERT INTO PRODUTOANUNCIO VALUES (36,43);
INSERT INTO PRODUTOANUNCIO VALUES (36,48);
INSERT INTO PRODUTOANUNCIO VALUES (37,44);
INSERT INTO PRODUTOANUNCIO VALUES (37,45);
INSERT INTO PRODUTOANUNCIO VALUES (38,52);
INSERT INTO PRODUTOANUNCIO VALUES (38,54);
INSERT INTO PRODUTOANUNCIO VALUES (39,12);
INSERT INTO PRODUTOANUNCIO VALUES (39,29);
INSERT INTO PRODUTOANUNCIO VALUES (40,61);
INSERT INTO PRODUTOANUNCIO VALUES (41,29);
INSERT INTO PRODUTOANUNCIO VALUES (42,53);
INSERT INTO PRODUTOANUNCIO VALUES (46,57);
INSERT INTO PRODUTOANUNCIO VALUES (47,21);
INSERT INTO PRODUTOANUNCIO VALUES (47,22);
INSERT INTO PRODUTOANUNCIO VALUES (47,24);
INSERT INTO PRODUTOANUNCIO VALUES (47,40);
INSERT INTO PRODUTOANUNCIO VALUES (47,62);