-- PEDIDO
DELIMITER &&
 	CREATE PROCEDURE PEDIDO_INSERT (
 	IN V_TIVCODIGO INT,
	   V_STPCODIGO INT
	   V_ANUCODIGO INT,
	   V_CLICODIGO INT,
	   V_PEDDATAVENDA DATE,
	   V_PEDVALORFRETE DECIMAL,
	   V_PEDDATAPOSTAGEM DATE,
	   V_PEDDATAENTREGA DATE,
	   V_PEDVALORTOTAL DECIMAL,
	   V_PEDCODPOSTAGEM VARCHAR(255),
	   V_PEDOBSERVACAO VARCHAR(255)
   	)
	BEGIN
    	INSERT INTO PEDIDO (TIVCODIGO, STPCODIGO, ANUCODIGO, CLICODIGO, PEDDATAVENDA, PEDVALORFRETE, PEDDATAPOSTAGEM, PEDDATAENTREGA, PEDVALORTOTAL, PEDCODIGOPOSTAGEM, PEDOBSERVACAO) VALUES (V_TIVCODIGO, V_STPCODIGO, V_ANUCODIGO, V_CLICODIGO, V_PEDDATAVENDA, V_PEDVALORFRETE, V_PEDDATAPOSTAGEM, V_PEDDATAENTREGA, V_PEDVALORTOTAL, V_PEDCODIGOPOSTAGEM, V_PEDOBSERVACAO);
  	END
&&

DELIMITER &&
 	CREATE PROCEDURE PEDIDO_UPDATE (
	IN V_PEDCODIGO INT,
	   V_TIVCODIGO INT,
	   V_STPCODIGO INT
	   V_ANUCODIGO INT,
	   V_CLICODIGO INT,
	   V_PEDDATAVENDA DATE,
	   V_PEDVALORFRETE DECIMAL,
	   V_PEDDATAPOSTAGEM DATE,
	   V_PEDDATAENTREGA DATE,
	   V_PEDVALORTOTAL DECIMAL,
	   V_PEDCODPOSTAGEM VARCHAR(255),
	   V_PEDOBSERVACAO VARCHAR(255)
   	)
	BEGIN
    	UPDATE PEDIDO SET TIVCODIGO = V_TIVCODIGO, STPCODIGO = V_STPCODIGO, CLICODIGO = V_CLICODIGO, PEDDATAVENDA = V_PEDDATAVENDA, PEDVALORFRETE = V_PEDVALORFRETE, PEDDATAPOSTAGEM = V_PEDDATAPOSTAGEM, PEDDATAENTREGA = V_PEDDATAENTREGA, PEDVALORTOTAL = V_PEDVALORTOTAL,  PEDCODIGOPOSTAGEM = V_PEDCODIGOPOSTAGEM, PEDOBSERVACAO = V_PEDOBSERVACAO WHERE PEDCODIGO = V_PEDCODIGO;
  	END
&&

DELIMITER &&
 	CREATE PROCEDURE PEDIDO_DELETE (
	IN V_PEDCODIGO INT	   
   	)
	BEGIN
    	DELETE FROM PEDIDO WHERE PEDCODIGO = V_PEDCODIGO;
  	END
&&

-- CLIENTE
DELIMITER &&




 	CREATE PROCEDURE CLIENTE_INSERT (
	IN V_CLINOME VARCHAR(255),
	   V_CLIEMAIL VARCHAR(255)	   
   	)
	BEGIN
    	INSERT INTO CLIENTE (CLINOME, CLIEMAIL) VALUES (V_CLINOME, V_CLIEMAIL);
  	END
&&

DELIMITER &&
 	CREATE PROCEDURE CLIENTE_UPDATE (
	IN  V_CLICODIGO INT,
		V_CLINOME VARCHAR(255),
	   	V_CLIEMAIL VARCHAR(255)	   
   	)
	BEGIN
    	UPDATE CLIENTE SET CLINOME = V_CLINOME, CLIEMAIL = V_CLIEMAIL WHERE CLICODIGO = V_CLICODIGO;
  	END
&&

DELIMITER &&
 	CREATE PROCEDURE CLIENTE_DELETE (
	IN  V_CLICODIGO INT		  
   	)
	BEGIN
    	DELETE FROM CLIENTE WHERE CLICODIGO = V_CLICODIGO;
  	END
&&


DELIMITER 
CREATE PROCEDURE PRODUTO_INSERT (
 	IN V_PRONOME VARCHAR(255),
	   V_PROESTOQUEMIN INT,
	   V_PROISATIVO BOOL 
   	)
	BEGIN
    	INSERT INTO PRODUTO (PRONOME, PROESTOQUEMIN, PROISATIVO) VALUES (V_PRONOME, V_PROESTOQUEMIN, V_PROISATIVO);
  	END
&&
    	
DELIMITER &&
CREATE PROCEDURE PRODUTO_UPDATE (

 	IN 
V_PROCODIGO INT,
 	V_PRONOME VARCHAR(255),
	   V_PROESTOQUEMIN INT,
	   V_PROISATIVO BOOL 
   	)
	BEGIN

    	UPDATE PRODUTO SET PRONOME = V_PRONOME, PROESTOQUEMIN = V_PROESTOQUEMIN, PROISATIVO = V_PROISATIVO WHERE PROCODIGO = V_PROCODIGO;
  	END
    &&

DELIMITER &&
 	CREATE PROCEDURE PRODUTO_DELETE (
	IN V_PROCODIGO INT	   
   	)
	BEGIN
    	DELETE FROM PRODUTO WHERE PROCODIGO = V_PROCODIGO;
  	END
&&







DELIMITER &&
 	CREATE PROCEDURE PRODUTO_DELETE (
	IN V_PROCODIGO INT	   
   	)
	BEGIN
    	DELETE FROM PRODUTO WHERE PROCODIGO = V_PROCODIGO;
  	END
&&





DELIMITER &&
CREATE PROCEDURE PRODUTOESTOQUE_INSERT (
 	IN V_PROCODIGO INT,
	   V_ESTPRECO DECIMAL,
	   V_ESTQUANTIDADE INT
	  
   	)
	BEGIN
    	INSERT INTO produtoestoque (PROCODIGO, ESTPRECO, ESTQUANTIDADE) VALUES (V_PROCODIGO, V_ESTPRECO,V_ESTQUANTIDADE);
  	END
&&

DELIMITER &&
 	CREATE PROCEDURE PRODTUTOESTOQUE_UPDATE (
	IN
	V_ESTCODIGO INT, 
	V_PROCODIGO INT,
	   V_ESTPRECO DECIMAL,
	   V_ESTQUANTIDADE INT
	   
   	)
	BEGIN
    	UPDATE PRODUTOESTOQUE SET PROCODIGO = V_PROCODIGO, ESTPRECO = V_ESTPRECO, ESTQUANTIDADE = V_ESTQUANTIDADE  WHERE ESTCODIGO = V_ESTCODIGO;
  	END
&&

DELIMITER &&
 	CREATE PROCEDURE PRODUTOESTOQUE_DELETE (
	IN V_ESTCODIGO INT	   
   	)
	BEGIN
    	DELETE FROM PRODUTOESTOQUE WHERE ESTCODIGO = V_ESTCODIGO;
  	END
&&

CALL PRODUTOESTOQUE_DELETE (1);