CALL PEDIDO_SELECT(null,'2016-05-24',null,null,null,null,null,null,null);

DROP PROCEDURE IF EXISTS PEDIDO_SELECT;

SELECT * FROM PEDIDO where pedCodigo = 32;

SELECT * FROM itenspedido where pedCodigo = 38;

SELECT * FROM tipoMovimentacao;

DESC itenspedido;

INSERT INTO itensPedido VALUES (36,25,25.90,90.99,1,9.99);

DROP PROCEDURE IF EXISTS ITENSPEDIDO_INSERT;
DELIMITER &&
 	CREATE PROCEDURE ITENSPEDIDO_INSERT (
 	IN V_PEDCODIGO INT,
	   V_PROCODIGO INT,
	   V_ITPVALORVENDA DECIMAL(8,2),
	   V_ITPVALORCOMPRA DECIMAL(8,2),
	   V_ITPQUANTIDADE INT,
	   V_ITPTAXA DECIMAL(8,2)
   	)
	BEGIN
    	INSERT INTO ITENSPEDIDO (PEDCODIGO,PROCODIGO,ITPVALORVENDA,ITPVALORCOMPRA,ITPQUANTIDADE,ITPTAXA) VALUES (V_PEDCODIGO, V_PROCODIGO, V_ITPVALORVENDA,
		V_ITPVALORCOMPRA,V_ITPQUANTIDADE,V_ITPTAXA);
  	END
&&

SELECT * FROM produto WHERE proQuantidade > 0 and proCodigo = 21;

SELECT * FROM outrasmovimentacoes;
SELECT * FROM pedido where pedCodigo = 39;
SELECT * FROM itenspedido where pedCodigo = 39;