 -- INNER JOIN

-- INSERT NÃO TEM CÓDIGO 
-- UPDATE TEM CÓDIGO MAS NÃO ATUALIZA ELE SÓ USA NO WHERE
-- DROP PROCEDURE NOME_PROCEDURE

SELECT TIMDESCRICAO, MOVDESCRICAO, MOVVALOR FROM OUTRASMOVIMENTACOES INNER JOIN TIPOMOVIMENTACAO ON OUTRASMOVIMENTACOES.TIMCODIGO = TIPOMOVIMENTACAO.TIMCODIGO;

CORRETO
DESC STATUSPEDIDO;
SELECT * FROM STATUSPEDIDO_INSERT;
CALL STATUSPEDIDO_INSERT ("FRANCO");
CALL STATUSPEDIDO_UPDATE (1,"MARCA");
CALL STATUSPEDIDO_DELETE (4);

CORRETO
DESC STATUSANUNCIO;
SELECT * FROM STATUSANUNCIO;
CALL STATUSANUNCIO_INSERT ("EURO");
CALL STATUSANUNCIO_UPDATE (1, "UNICA");
CALL STATUSANUNCIO_INSERT ("REFERENCIA");
CALL STATUSANUNCIO_UPDATE ("MARCA",2);
CALL STATUSANUNCIO_DELETE (9);

CORRETO
DESC PRODUTO
SELECT * FROM PRODUTO;    
DESC TBL_PRODUTO;
DROP TABLE PRODUTO; FORENKEY---
CALL PRODUTO_INSERT ("PRODUTO",50,TRUE);
CALL PRODUTO_UPDATE (2,"BOM",50,30);
CALL PRODUTO_DELETE (6);
CALL PRODUTO_INSERT ("PRODUTO","INT",TRUE);
CALL PRODUTO_UPDATE (4,"PROTUDO",8,50);
CALL PRODUTO_DELETE (1);
CALL PRODUTO_UPDATE ("BOM","INT","FALSE");
CALL PRODUTO_INSERT ("PRODUTO","INT",TRUE);

CORRETO
DESC usuario;
SELECT * FROM USUARIO;
CALL USUARIO_INSERT ("JOSAFA","MARIA",TRUE,FALSE);
CALL USUARIO_UPDATE (1,"JOSE","JOAO",TRUE,FALSE);
CALL USUARIO_DELETE ("VALBER");

CORRETO
SELECT * FROM TIPOAVALIACOES;
DESC TIPOAVALIACOES;
CALL TIPOAVALIACOES_INSERT (12);
CALL TIPOAVALIACOES_UPDATE (3,12);
DROP PROCEDURE TIPOAVALIACOES_UPDATE;
CALL TIPOAVALIACOES_DELETE (3);

CORRETO
SELECT * FROM TIPOANUNCIO;
DESC TIPOANUNCIO;
DROP PROCEDURE TIPOANUNCIO_UPDATE;
DROP PROCEDURE TIPOANUNCIO_DELETE;
DROP PROCEDURE TIPOANUNCIO_INSERT; 
CALL TIPOANUNCIO_INSERT (7,"O MOCHILAO",80.0);
CALL TIPOANUNCIO_DELETE (5);
CALL TIPOANUNCIO_UPDATE ("3","O MOCHILAO",30);


SELECT * FROM CLIENTE;
DROP PROCEDURE ANUNCIO_INSERT;

DROP PROCEDURE CLIENTE_INSERT;

CALL CLIENTE_INSERT ("CAMILA", "CAMILA@GMAIL.COM");
CALL CLIENTE_INSERT ("CAMILA", "CAMILA@GMAIL.COM");
CALL CLIENTE_INSERT ("CAMILA", "CAMILA@GMAIL.COM");
CALL CLIENTE_INSERT ("CAMILA", "CAMILA@GMAIL.COM");
CALL CLIENTE_UPDATE (1, "JOAO", "JOAO@GMAIL.COM");
CALL CLIENTE_DELETE (2);
CORRETO
DESC CLIENTE;
SELECT * FROM CLIENTE;
CALL CLIENTE_INSERT ("JOANA", "JOANA@GMAIL.COM");
CALL CLIENTE_UPDATE (3, "CAMILA", "CAMILA@GMAIL.COM");
CALL CLIENTE_DELETE (8);
DROP PROCEDURE CLIENTE_DELETE;

CORRETO
DESC TIPOMOVIMENTACAO;
SELECT * FROM TIPOMOVIMENTACAO;
CALL TIPOMOVIMENTACAO_INSERT ("JOAO",TRUE);
CALL TIPOMOVIMENTACAO_INSERT (12,TRUE);
CALL TIPOMOVIMENTACAO_UPDATE (3,12);
CALL TIPOMOVIMENTACAO_DELETE (3);
DROP PROCEDURE TIPOMOVIMENTACAO_UPDATE;
DROP PROCEDURE TIPOMOVIMENTACAO_INSERT;
DROP PROCEDURE TIPOMOVIMENTACAO_DELETE;


DESC ENTRADA;
SELECT * FROM ENTRADA;
CALL ITENSENTRADA_INSERT ("ZIPERS",100.0,"MOCHILA REFORÇADA");
CALL ENTRADA_INSERT ("MOCHILA",10.0,"MOCHILA DUPLA");
DROP PROCEDURE ENTRADA_INSERT;
CALL ENTRADA_DELETE(1);
CALL ENTRADA_UPDATE (50"MOCHILA SIMPLES"20);ERRO
DESC ENTRADA;
SELECT * FROM ENTRADA;
CALL ITENSENTRADA_INSERT (1,"ZIPERS",50.0,"MOCHILA REFORCADA");
CALL ENTRADA_INSERT (1,"MOCHILA",20.0,"MOCHILA DUPLA");
DROP PROCEDURE ENTRADA_INSERT;
DROP PROCEDURE ENTRADA_UPDATE;
DROP PROCEDURE ENTRADA_DELETE;
CALL ENTRADA_DELETE(17);
CALL ENTRADA_UPDATE (1,12,30,"AZUL");???
CALL ITENSENTRADA_INSERT (1,"ZIPERS",100.0,"MOCHILA REFORÇADA");

CORRETO
DESC OUTRASMOVIMENTACOES;
SELECT * FROM OUTRASMOVIMENTACOES;
CALL OUTRASMOVIMENTACOES_INSERT (1,"JOAO",60,"12/10/2020");
CALL OUTRASMOVIMENTACOES_UPDATE (3,12);
CALL OUTRASOMOVIMENTACOES_DELETE (3);
DROP PROCEDURE PRODUTOESTOQUE_UPDATE;
DROP PROCEDURE OUTRASMOVIMENTACOES_INSERT;
DROP PROCEDURE OUTRASMOVIMENTACOES_DELETE;



DESC PRODUTOESTOQUE
SELECT * FROM PRODUTOESTOQUE;    
DESC TBL_PRODUTOESTOQUE;
DROP PROCEDURE PRODUTOESTOQUE; FORENKEY---
DROP PROCEDURA PRODUTOESTOQUE_INSERT;
DROP PROCEDURE PRODUTOESTOQUE_UPDATE;
CALL PRODUTOESTOQUE_INSERT ("PRODUTO",50,TRUE);
CALL PRODUTOESTOQUE_UPDATE (2,"BOM",50,30);
CALL PRODUTOESTOQUE_DELETE (6);
CALL PRODUTOESTOQUE_INSERT ("PRODUTO","INT",TRWE);
CALL PRODUTOESTOQUE_UPDATE (4,"PROTUDO",8,50);
CALL PRODUTOESTOQUE_DELETE (1);
CALL PRODUTOESTOQUE_UPDATE ("BOM","INT","FALSE");
CALL PRODUTOESTOQUE_INSERT ("PRODUTO","INT",TRWE);

CORRETO
DESC PRODUTOESTOQUE;
SELECT * FROM PRODUTOESTOQUE;    
DESC TBL_PRODUTOESTOQUE;
DROP PROCEDURE PRODUTOESTOQUE; FORENKEY---
DROP PROCEDURE PRODUTOESTOQUE_INSERT;
DROP PROCEDURE PRODUTOESTOQUE_UPDATE;
CALL PRODUTOESTOQUE_INSERT (2,40,TRUE);
CALL PRODUTOESTOQUE_UPDATE (4,2,50,60);
CALL PRODUTOESTOQUE_DELETE (10);

CORRETO
DESC ANUNCIO;
SELECT * FROM ANUNCIO;
DROP PROCEDURE ANUNCIO_INSERT;
DROP PROCEDURE ANUNCIO_UPDATE;
DROP PROCEDURE ANUNCIO_DELETE;
CALL ANUNCIO_INSERT (5,4,"JANEIRO",20,"2018/12/10",TRUE);
CALL ANUNCIO_UPDATE (3,3,2016,100,"2025/10/10",TRUE);
CALL ANUNCIO_DELETE (10);

CORRETO
DESC ITENSENTRADA;
SELECT * FROM ITENSENTRADA;
DROP PROCEDURE ITENSENTRADA_INSERT;
DROP PROCEDURE ITENSENTRADA_UPDATE;
DROP PROCEDURE ITENSENTRADA_DELETE;
CALL ITENSENTRADA_DELETE(4);
CALL ITENSENTRADA_UPDATE (4,12,30,10,10);
CALL ITENSENTRADA_INSERT (4,"3",100.0,10.00,10.00);


DESC PEDIDO;
SELECT * FROM PEDIDO;
DROP PROCEDURE PEDIDO_INSERT;
DROP PROCEDURE PEDIDO_UPDATE;
DROP PROCEDURE PEDIDO_DELETE;
CALL PEDIDO_DELETE(4);
CALL PEDIDO_UPDATE (4,12,30,10,10);
CALL PEDIDO_INSERT (2,1,1,1,"2016/10/12","10.0","2016/11/11","2017/12/12",100.0,"EXCELENTE","PRODUTO EXCELENTE");
SELECT * FROM ITENSPEDIDO;
SELECT * FROM PEDIDO;
SELECT * FROM  TIPOAVALIACOES;
SELECT * FROM STATUSPEDIDO;
SELECT * FROM ANUNCIO;

DESC ITENSPEDIDO;
SELECT * FROM ITENSPEDIDO;
DROP PROCEDURE ITENSPEDIDO_INSERT;
DROP PROCEDURE ITENSPEDIDO_UPDATE;
DROP PROCEDURE ITENSPEDIDO_DELETE;
CALL ITENSPEDIDO_DELETE(4);
CALL ITENSPEDIDO_UPDATE (4,12,30,10,10);
CALL ITENSPEDIDO_INSERT (1,1,100.0,10.00,10.00);
SELECT * FROM ITENSPEDIDO;
SELECT * FROM PEDIDO;
SELECT * FROM  TIPOAVALIACOES;
SELECT * FROM STATUSPEDIDO;
SELECT * FROM ANUNCIO;